### ISSUE TITLE
[Improvement] In itemization parser, more link to items versions

### ISSUE THREAD

**Issue by Krabator** [Kruhlmann/classicdb_bot#35]
**Describe the evolution**
When I am using the item bot, I want to have info on specific item
In the itemization parser I would like to have access to each item versions when I start a search on it.

**Screenshots**
![item bot evol](https://user-images.githubusercontent.com/14138462/61122527-48876200-a4a2-11e9-929b-bbb2758bdb8c.png)

**Comment by Kruhlmann** [comment]
There is no distinction between patches on the site itself, and as such the link in the top (https://itemization.info/item/17076) will take you to all version of the item as shown below.

![bonereaver](https://user-images.githubusercontent.com/3380818/61123339-6ce43e00-a4a4-11e9-81c6-b57de671e0d5.PNG)

It could still be useful to let the user know all the patches where the item was changed.
