### ISSUE TITLE
[Improvement] short -i or -c argument for itemization or classic db

### ISSUE THREAD

**Issue by Krabator** [Kruhlmann/classicdb_bot#36]
**Describe the evolution**
Thank for adding the (classicdb) and (itemization) argument, it's very helpful.
But for ease of use, is it possible to have very short argument such as "-i" for (itemization) and "-c" for (classicdb) please ?

**Comment by Kruhlmann** [comment]
As long as there are only 2 parsers it might be a good idea to shorten the parser identifiers. I'm considering whether [...]c and [...]i would be more useful, since we're trying to type as little as possible.
