### ISSUE TITLE
Ignore punctuation marks from text match/search e.g '

### ISSUE THREAD

**Issue by rockBreaker** [Kruhlmann/classicdb_bot#39]
**Describe the bug**
[edgemasters] ->Unable to find item "edgemasters"
[edgemaster's] -> Edgemaster's Handguards (latest patch)

It would be nice to match text without using punctuation marks such as '

**To Reproduce**
Search for [edgemasters]
See no results

**Expected behavior**
expected to see edgemasters result

**Screenshots**
[link to screenshot](https://cdn.discordapp.com/attachments/456930992557654037/601866269066526740/Screen_Shot_2019-07-19_at_21.00.49.png)

**Environment (please complete the following information):**
 - OS: mac discord
 **Parser**
 
 If this bug is relevant only to specific parsers please select the ones it applies to below.
 - [x] ClassicDB
 - [x] Itemization
 

**Additional context**

**Comment by Kruhlmann** [comment]
Talked with @magey this is not possible from he point of view of the bot. It will have to be fixed in the itemization.info API.
